#!/bin/sh
qsub -N VLP_1 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 1 /home/jbmasson/all_treatment/WT'
qsub -N VLP_2 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 2 /home/jbmasson/all_treatment/WT'
qsub -N VLP_3 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 3 /home/jbmasson/all_treatment/WT'
qsub -N VLP_4 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 4 /home/jbmasson/all_treatment/WT'
qsub -N VLP_5 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 5 /home/jbmasson/all_treatment/WT'
qsub -N VLP_6 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 6 /home/jbmasson/all_treatment/WT'
qsub -N VLP_7 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 7 /home/jbmasson/all_treatment/WT'
qsub -N VLP_8 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 8 /home/jbmasson/all_treatment/WT'
qsub -N VLP_9 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 9 /home/jbmasson/all_treatment/WT'
qsub -N VLP_10 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 10 /home/jbmasson/all_treatment/WT'
qsub -N VLP_11 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 11 /home/jbmasson/all_treatment/WT'
qsub -N VLP_12 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 12 /home/jbmasson/all_treatment/WT'
qsub -N VLP_13 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 13 /home/jbmasson/all_treatment/WT'
qsub -N VLP_14 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 14 /home/jbmasson/all_treatment/WT'
qsub -N VLP_15 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 15 /home/jbmasson/all_treatment/WT'
qsub -N VLP_16 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 16 /home/jbmasson/all_treatment/WT'
qsub -N VLP_17 -j y -o /dev/null -b y -cwd -V 'sh wrapper_pipeline_VLP.sh 17 /home/jbmasson/all_treatment/WT'
