#!/bin/sh
sbatch -J VLP_1 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 1 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_2 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 2 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_3 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 3 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_4 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 4 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_5 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 5 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_6 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 6 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_7 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 7 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_8 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 8 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_9 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 9 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_10 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 10 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_11 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 11 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_12 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 12 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_13 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 13 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_14 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 14 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_15 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 15 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_16 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 16 /home/jbmasson/all_treatment/WT'
sbatch -J VLP_17 --mem-per-cpu=3000MB  -o /dev/null --wrap='sh wrapper_pipeline_VLP.sh 17 /home/jbmasson/all_treatment/WT'
